spring.application.name=fruit-monthly-price
server.port=8000

# We use port 8765 for the config server since port 8888 was not available
spring.config.import=optional:configserver:http://localhost:8765

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true
fmp.file.path=data/FMP.xlsx
